namespace Game
{
    public enum SpawnTypeExplosion
    {
        DEATH_EXPLOSION,
        KAMIKAZE_EXPLOSION,
        ENERGY_MISSILE_EXPLOSION,
        FIRE_MISSILE_EXPLOION,
        FROST_MISSILE_EXPLOSION,
        LASER_MISSILE_EXPLOSION,
        LIGHTNING_MISSILE_EXPLOSION,
        MYSTIC_MISSILE_EXPLOSION,
        NOVA_MISSILE_EXPLOSION,
        SHADOW_MISSILE_EXPLOSION,
        SOUL_MISSILE_EXPLOSION,
    }
}